#Docker Work na BSDK

name: Discord Bot

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           git config --global credential.helper store
           echo "https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@${{ secrets.CREDS }} DXCT
       - name: Running BOT
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd DXCT
           pip3 install discord.py html2image~=2.0.1 python-dotenv~=0.19.0 tgcrypto requests apscheduler asyncio aiohttp~=3.7.4.post0
           python3 -m bot
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
